run:
  dir: ${paths.run_dir}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${paths.run_dir}/hydra.log

defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
