# @package _global_

defaults:
  - model: latent_attention
  - data: mu2030pu
  - data_load: default
  - optim: default
  - loss: pt_mask
  - paths: khu
  - torch: default
  - hydra: default
  - misc: default
  - _self_
  - mode: null

exp: tts
run: ${now:%y%m%d-%H%M%S}_${slug:2}
