dataset:
  _target_: muonly.data.TrackerTrackSelectionDataset
  _partial_: true
  tracker_track_features: ${data.tracker_track.features}
  dt_segment_features: ${data.dt_segment.features}
  csc_segment_features: ${data.csc_segment.features}
  gem_segment_features: ${data.gem_segment.features}
  rpc_hit_features: ${data.rpc_hit.features}
  gem_hit_features: ${data.gem_hit.features}
  target_key: ${data.target_key}

train:
  path: ${paths.train_file}
  max_events: null

val:
  path: ${paths.val_file}
  max_events: null

test:
  path: ${paths.test_file}
  max_events: null
